//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PM.TaskBiz.HuangShiCCBTask.ORM
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class GovPmBidOnline_BusinessEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“GovPmBidOnline_BusinessEntities”部分中的连接字符串初始化新 GovPmBidOnline_BusinessEntities 对象。
        /// </summary>
        public GovPmBidOnline_BusinessEntities() : base("name=GovPmBidOnline_BusinessEntities", "GovPmBidOnline_BusinessEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 GovPmBidOnline_BusinessEntities 对象。
        /// </summary>
        public GovPmBidOnline_BusinessEntities(string connectionString) : base(connectionString, "GovPmBidOnline_BusinessEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 GovPmBidOnline_BusinessEntities 对象。
        /// </summary>
        public GovPmBidOnline_BusinessEntities(EntityConnection connection) : base(connection, "GovPmBidOnline_BusinessEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_BASE_Banks> T_BASE_Banks
        {
            get
            {
                if ((_T_BASE_Banks == null))
                {
                    _T_BASE_Banks = base.CreateObjectSet<T_BASE_Banks>("T_BASE_Banks");
                }
                return _T_BASE_Banks;
            }
        }
        private ObjectSet<T_BASE_Banks> _T_BASE_Banks;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_ZTB_BidMoneyPayReturn> T_ZTB_BidMoneyPayReturn
        {
            get
            {
                if ((_T_ZTB_BidMoneyPayReturn == null))
                {
                    _T_ZTB_BidMoneyPayReturn = base.CreateObjectSet<T_ZTB_BidMoneyPayReturn>("T_ZTB_BidMoneyPayReturn");
                }
                return _T_ZTB_BidMoneyPayReturn;
            }
        }
        private ObjectSet<T_ZTB_BidMoneyPayReturn> _T_ZTB_BidMoneyPayReturn;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_ZTB_DepositCCB> T_ZTB_DepositCCB
        {
            get
            {
                if ((_T_ZTB_DepositCCB == null))
                {
                    _T_ZTB_DepositCCB = base.CreateObjectSet<T_ZTB_DepositCCB>("T_ZTB_DepositCCB");
                }
                return _T_ZTB_DepositCCB;
            }
        }
        private ObjectSet<T_ZTB_DepositCCB> _T_ZTB_DepositCCB;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 T_BASE_Banks EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_BASE_Banks(T_BASE_Banks t_BASE_Banks)
        {
            base.AddObject("T_BASE_Banks", t_BASE_Banks);
        }
    
        /// <summary>
        /// 用于向 T_ZTB_BidMoneyPayReturn EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_ZTB_BidMoneyPayReturn(T_ZTB_BidMoneyPayReturn t_ZTB_BidMoneyPayReturn)
        {
            base.AddObject("T_ZTB_BidMoneyPayReturn", t_ZTB_BidMoneyPayReturn);
        }
    
        /// <summary>
        /// 用于向 T_ZTB_DepositCCB EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_ZTB_DepositCCB(T_ZTB_DepositCCB t_ZTB_DepositCCB)
        {
            base.AddObject("T_ZTB_DepositCCB", t_ZTB_DepositCCB);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GovPmBidOnline_BusinessModel", Name="T_BASE_Banks")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_BASE_Banks : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_BASE_Banks 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="userId">UserId 属性的初始值。</param>
        /// <param name="unitId">UnitId 属性的初始值。</param>
        public static T_BASE_Banks CreateT_BASE_Banks(global::System.Guid id, global::System.Guid userId, global::System.Guid unitId)
        {
            T_BASE_Banks t_BASE_Banks = new T_BASE_Banks();
            t_BASE_Banks.Id = id;
            t_BASE_Banks.UserId = userId;
            t_BASE_Banks.UnitId = unitId;
            return t_BASE_Banks;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UnitId
        {
            get
            {
                return _UnitId;
            }
            set
            {
                OnUnitIdChanging(value);
                ReportPropertyChanging("UnitId");
                _UnitId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitId");
                OnUnitIdChanged();
            }
        }
        private global::System.Guid _UnitId;
        partial void OnUnitIdChanging(global::System.Guid value);
        partial void OnUnitIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitName
        {
            get
            {
                return _UnitName;
            }
            set
            {
                OnUnitNameChanging(value);
                ReportPropertyChanging("UnitName");
                _UnitName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitName");
                OnUnitNameChanged();
            }
        }
        private global::System.String _UnitName;
        partial void OnUnitNameChanging(global::System.String value);
        partial void OnUnitNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BankName
        {
            get
            {
                return _BankName;
            }
            set
            {
                OnBankNameChanging(value);
                ReportPropertyChanging("BankName");
                _BankName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BankName");
                OnBankNameChanged();
            }
        }
        private global::System.String _BankName;
        partial void OnBankNameChanging(global::System.String value);
        partial void OnBankNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BankNum
        {
            get
            {
                return _BankNum;
            }
            set
            {
                OnBankNumChanging(value);
                ReportPropertyChanging("BankNum");
                _BankNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BankNum");
                OnBankNumChanged();
            }
        }
        private global::System.String _BankNum;
        partial void OnBankNumChanging(global::System.String value);
        partial void OnBankNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GongYao
        {
            get
            {
                return _GongYao;
            }
            set
            {
                OnGongYaoChanging(value);
                ReportPropertyChanging("GongYao");
                _GongYao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GongYao");
                OnGongYaoChanged();
            }
        }
        private global::System.String _GongYao;
        partial void OnGongYaoChanging(global::System.String value);
        partial void OnGongYaoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerchantId
        {
            get
            {
                return _MerchantId;
            }
            set
            {
                OnMerchantIdChanging(value);
                ReportPropertyChanging("MerchantId");
                _MerchantId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MerchantId");
                OnMerchantIdChanged();
            }
        }
        private global::System.String _MerchantId;
        partial void OnMerchantIdChanging(global::System.String value);
        partial void OnMerchantIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PosId
        {
            get
            {
                return _PosId;
            }
            set
            {
                OnPosIdChanging(value);
                ReportPropertyChanging("PosId");
                _PosId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PosId");
                OnPosIdChanged();
            }
        }
        private global::System.String _PosId;
        partial void OnPosIdChanging(global::System.String value);
        partial void OnPosIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BranchId
        {
            get
            {
                return _BranchId;
            }
            set
            {
                OnBranchIdChanging(value);
                ReportPropertyChanging("BranchId");
                _BranchId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BranchId");
                OnBranchIdChanged();
            }
        }
        private global::System.String _BranchId;
        partial void OnBranchIdChanging(global::System.String value);
        partial void OnBranchIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountName
        {
            get
            {
                return _AccountName;
            }
            set
            {
                OnAccountNameChanging(value);
                ReportPropertyChanging("AccountName");
                _AccountName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountName");
                OnAccountNameChanged();
            }
        }
        private global::System.String _AccountName;
        partial void OnAccountNameChanging(global::System.String value);
        partial void OnAccountNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GovPmBidOnline_BusinessModel", Name="T_ZTB_BidMoneyPayReturn")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_ZTB_BidMoneyPayReturn : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_ZTB_BidMoneyPayReturn 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="autoId">AutoId 属性的初始值。</param>
        public static T_ZTB_BidMoneyPayReturn CreateT_ZTB_BidMoneyPayReturn(global::System.Guid id, global::System.Int32 autoId)
        {
            T_ZTB_BidMoneyPayReturn t_ZTB_BidMoneyPayReturn = new T_ZTB_BidMoneyPayReturn();
            t_ZTB_BidMoneyPayReturn.Id = id;
            t_ZTB_BidMoneyPayReturn.AutoId = autoId;
            return t_ZTB_BidMoneyPayReturn;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CaseId
        {
            get
            {
                return _CaseId;
            }
            set
            {
                OnCaseIdChanging(value);
                ReportPropertyChanging("CaseId");
                _CaseId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CaseId");
                OnCaseIdChanged();
            }
        }
        private Nullable<global::System.Guid> _CaseId;
        partial void OnCaseIdChanging(Nullable<global::System.Guid> value);
        partial void OnCaseIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> BidderId
        {
            get
            {
                return _BidderId;
            }
            set
            {
                OnBidderIdChanging(value);
                ReportPropertyChanging("BidderId");
                _BidderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BidderId");
                OnBidderIdChanged();
            }
        }
        private Nullable<global::System.Guid> _BidderId;
        partial void OnBidderIdChanging(Nullable<global::System.Guid> value);
        partial void OnBidderIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PayTime
        {
            get
            {
                return _PayTime;
            }
            set
            {
                OnPayTimeChanging(value);
                ReportPropertyChanging("PayTime");
                _PayTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayTime");
                OnPayTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PayTime;
        partial void OnPayTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPayTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PayMoney
        {
            get
            {
                return _PayMoney;
            }
            set
            {
                OnPayMoneyChanging(value);
                ReportPropertyChanging("PayMoney");
                _PayMoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayMoney");
                OnPayMoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _PayMoney;
        partial void OnPayMoneyChanging(Nullable<global::System.Decimal> value);
        partial void OnPayMoneyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayType
        {
            get
            {
                return _PayType;
            }
            set
            {
                OnPayTypeChanging(value);
                ReportPropertyChanging("PayType");
                _PayType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayType");
                OnPayTypeChanged();
            }
        }
        private global::System.String _PayType;
        partial void OnPayTypeChanging(global::System.String value);
        partial void OnPayTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardNum
        {
            get
            {
                return _CardNum;
            }
            set
            {
                OnCardNumChanging(value);
                ReportPropertyChanging("CardNum");
                _CardNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardNum");
                OnCardNumChanged();
            }
        }
        private global::System.String _CardNum;
        partial void OnCardNumChanging(global::System.String value);
        partial void OnCardNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsCheck
        {
            get
            {
                return _IsCheck;
            }
            set
            {
                OnIsCheckChanging(value);
                ReportPropertyChanging("IsCheck");
                _IsCheck = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCheck");
                OnIsCheckChanged();
            }
        }
        private Nullable<global::System.Int32> _IsCheck;
        partial void OnIsCheckChanging(Nullable<global::System.Int32> value);
        partial void OnIsCheckChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ReturnManId
        {
            get
            {
                return _ReturnManId;
            }
            set
            {
                OnReturnManIdChanging(value);
                ReportPropertyChanging("ReturnManId");
                _ReturnManId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnManId");
                OnReturnManIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ReturnManId;
        partial void OnReturnManIdChanging(Nullable<global::System.Guid> value);
        partial void OnReturnManIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReturnTime
        {
            get
            {
                return _ReturnTime;
            }
            set
            {
                OnReturnTimeChanging(value);
                ReportPropertyChanging("ReturnTime");
                _ReturnTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnTime");
                OnReturnTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReturnTime;
        partial void OnReturnTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnReturnTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReturnWindow
        {
            get
            {
                return _ReturnWindow;
            }
            set
            {
                OnReturnWindowChanging(value);
                ReportPropertyChanging("ReturnWindow");
                _ReturnWindow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReturnWindow");
                OnReturnWindowChanged();
            }
        }
        private global::System.String _ReturnWindow;
        partial void OnReturnWindowChanging(global::System.String value);
        partial void OnReturnWindowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsReturn
        {
            get
            {
                return _IsReturn;
            }
            set
            {
                OnIsReturnChanging(value);
                ReportPropertyChanging("IsReturn");
                _IsReturn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsReturn");
                OnIsReturnChanged();
            }
        }
        private Nullable<global::System.Int32> _IsReturn;
        partial void OnIsReturnChanging(Nullable<global::System.Int32> value);
        partial void OnIsReturnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UnitId
        {
            get
            {
                return _UnitId;
            }
            set
            {
                OnUnitIdChanging(value);
                ReportPropertyChanging("UnitId");
                _UnitId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitId");
                OnUnitIdChanged();
            }
        }
        private Nullable<global::System.Guid> _UnitId;
        partial void OnUnitIdChanging(Nullable<global::System.Guid> value);
        partial void OnUnitIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BankCardNum
        {
            get
            {
                return _BankCardNum;
            }
            set
            {
                OnBankCardNumChanging(value);
                ReportPropertyChanging("BankCardNum");
                _BankCardNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BankCardNum");
                OnBankCardNumChanged();
            }
        }
        private global::System.String _BankCardNum;
        partial void OnBankCardNumChanging(global::System.String value);
        partial void OnBankCardNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BankName
        {
            get
            {
                return _BankName;
            }
            set
            {
                OnBankNameChanging(value);
                ReportPropertyChanging("BankName");
                _BankName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BankName");
                OnBankNameChanged();
            }
        }
        private global::System.String _BankName;
        partial void OnBankNameChanging(global::System.String value);
        partial void OnBankNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitCode
        {
            get
            {
                return _UnitCode;
            }
            set
            {
                OnUnitCodeChanging(value);
                ReportPropertyChanging("UnitCode");
                _UnitCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitCode");
                OnUnitCodeChanged();
            }
        }
        private global::System.String _UnitCode;
        partial void OnUnitCodeChanging(global::System.String value);
        partial void OnUnitCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CaseCode
        {
            get
            {
                return _CaseCode;
            }
            set
            {
                OnCaseCodeChanging(value);
                ReportPropertyChanging("CaseCode");
                _CaseCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CaseCode");
                OnCaseCodeChanged();
            }
        }
        private global::System.String _CaseCode;
        partial void OnCaseCodeChanging(global::System.String value);
        partial void OnCaseCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AutoId
        {
            get
            {
                return _AutoId;
            }
            set
            {
                OnAutoIdChanging(value);
                ReportPropertyChanging("AutoId");
                _AutoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoId");
                OnAutoIdChanged();
            }
        }
        private global::System.Int32 _AutoId;
        partial void OnAutoIdChanging(global::System.Int32 value);
        partial void OnAutoIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitName
        {
            get
            {
                return _UnitName;
            }
            set
            {
                OnUnitNameChanging(value);
                ReportPropertyChanging("UnitName");
                _UnitName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitName");
                OnUnitNameChanged();
            }
        }
        private global::System.String _UnitName;
        partial void OnUnitNameChanging(global::System.String value);
        partial void OnUnitNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProID
        {
            get
            {
                return _ProID;
            }
            set
            {
                OnProIDChanging(value);
                ReportPropertyChanging("ProID");
                _ProID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProID");
                OnProIDChanged();
            }
        }
        private global::System.String _ProID;
        partial void OnProIDChanging(global::System.String value);
        partial void OnProIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BidMoneyType
        {
            get
            {
                return _BidMoneyType;
            }
            set
            {
                OnBidMoneyTypeChanging(value);
                ReportPropertyChanging("BidMoneyType");
                _BidMoneyType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BidMoneyType");
                OnBidMoneyTypeChanged();
            }
        }
        private global::System.String _BidMoneyType;
        partial void OnBidMoneyTypeChanging(global::System.String value);
        partial void OnBidMoneyTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LinkPerson
        {
            get
            {
                return _LinkPerson;
            }
            set
            {
                OnLinkPersonChanging(value);
                ReportPropertyChanging("LinkPerson");
                _LinkPerson = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinkPerson");
                OnLinkPersonChanged();
            }
        }
        private global::System.String _LinkPerson;
        partial void OnLinkPersonChanging(global::System.String value);
        partial void OnLinkPersonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LinkPersonPhone
        {
            get
            {
                return _LinkPersonPhone;
            }
            set
            {
                OnLinkPersonPhoneChanging(value);
                ReportPropertyChanging("LinkPersonPhone");
                _LinkPersonPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinkPersonPhone");
                OnLinkPersonPhoneChanged();
            }
        }
        private global::System.String _LinkPersonPhone;
        partial void OnLinkPersonPhoneChanging(global::System.String value);
        partial void OnLinkPersonPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LinkPersonMobilTel
        {
            get
            {
                return _LinkPersonMobilTel;
            }
            set
            {
                OnLinkPersonMobilTelChanging(value);
                ReportPropertyChanging("LinkPersonMobilTel");
                _LinkPersonMobilTel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinkPersonMobilTel");
                OnLinkPersonMobilTelChanged();
            }
        }
        private global::System.String _LinkPersonMobilTel;
        partial void OnLinkPersonMobilTelChanging(global::System.String value);
        partial void OnLinkPersonMobilTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderNum
        {
            get
            {
                return _OrderNum;
            }
            set
            {
                OnOrderNumChanging(value);
                ReportPropertyChanging("OrderNum");
                _OrderNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderNum");
                OnOrderNumChanged();
            }
        }
        private global::System.String _OrderNum;
        partial void OnOrderNumChanging(global::System.String value);
        partial void OnOrderNumChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GovPmBidOnline_BusinessModel", Name="T_ZTB_DepositCCB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_ZTB_DepositCCB : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_ZTB_DepositCCB 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static T_ZTB_DepositCCB CreateT_ZTB_DepositCCB(global::System.Guid id)
        {
            T_ZTB_DepositCCB t_ZTB_DepositCCB = new T_ZTB_DepositCCB();
            t_ZTB_DepositCCB.ID = id;
            return t_ZTB_DepositCCB;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REQUEST_SN
        {
            get
            {
                return _REQUEST_SN;
            }
            set
            {
                OnREQUEST_SNChanging(value);
                ReportPropertyChanging("REQUEST_SN");
                _REQUEST_SN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REQUEST_SN");
                OnREQUEST_SNChanged();
            }
        }
        private global::System.String _REQUEST_SN;
        partial void OnREQUEST_SNChanging(global::System.String value);
        partial void OnREQUEST_SNChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUST_ID
        {
            get
            {
                return _CUST_ID;
            }
            set
            {
                OnCUST_IDChanging(value);
                ReportPropertyChanging("CUST_ID");
                _CUST_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CUST_ID");
                OnCUST_IDChanged();
            }
        }
        private global::System.String _CUST_ID;
        partial void OnCUST_IDChanging(global::System.String value);
        partial void OnCUST_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TX_CODE
        {
            get
            {
                return _TX_CODE;
            }
            set
            {
                OnTX_CODEChanging(value);
                ReportPropertyChanging("TX_CODE");
                _TX_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TX_CODE");
                OnTX_CODEChanged();
            }
        }
        private global::System.String _TX_CODE;
        partial void OnTX_CODEChanging(global::System.String value);
        partial void OnTX_CODEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TRAN_DATE
        {
            get
            {
                return _TRAN_DATE;
            }
            set
            {
                OnTRAN_DATEChanging(value);
                ReportPropertyChanging("TRAN_DATE");
                _TRAN_DATE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TRAN_DATE");
                OnTRAN_DATEChanged();
            }
        }
        private global::System.String _TRAN_DATE;
        partial void OnTRAN_DATEChanging(global::System.String value);
        partial void OnTRAN_DATEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TRAN_TIME
        {
            get
            {
                return _TRAN_TIME;
            }
            set
            {
                OnTRAN_TIMEChanging(value);
                ReportPropertyChanging("TRAN_TIME");
                _TRAN_TIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TRAN_TIME");
                OnTRAN_TIMEChanged();
            }
        }
        private global::System.String _TRAN_TIME;
        partial void OnTRAN_TIMEChanging(global::System.String value);
        partial void OnTRAN_TIMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TRAN_SQ
        {
            get
            {
                return _TRAN_SQ;
            }
            set
            {
                OnTRAN_SQChanging(value);
                ReportPropertyChanging("TRAN_SQ");
                _TRAN_SQ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TRAN_SQ");
                OnTRAN_SQChanged();
            }
        }
        private global::System.String _TRAN_SQ;
        partial void OnTRAN_SQChanging(global::System.String value);
        partial void OnTRAN_SQChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACCOUNT
        {
            get
            {
                return _ACCOUNT;
            }
            set
            {
                OnACCOUNTChanging(value);
                ReportPropertyChanging("ACCOUNT");
                _ACCOUNT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACCOUNT");
                OnACCOUNTChanged();
            }
        }
        private global::System.String _ACCOUNT;
        partial void OnACCOUNTChanging(global::System.String value);
        partial void OnACCOUNTChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACCOUNT_NAME
        {
            get
            {
                return _ACCOUNT_NAME;
            }
            set
            {
                OnACCOUNT_NAMEChanging(value);
                ReportPropertyChanging("ACCOUNT_NAME");
                _ACCOUNT_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACCOUNT_NAME");
                OnACCOUNT_NAMEChanged();
            }
        }
        private global::System.String _ACCOUNT_NAME;
        partial void OnACCOUNT_NAMEChanging(global::System.String value);
        partial void OnACCOUNT_NAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONEY
        {
            get
            {
                return _MONEY;
            }
            set
            {
                OnMONEYChanging(value);
                ReportPropertyChanging("MONEY");
                _MONEY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONEY");
                OnMONEYChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONEY;
        partial void OnMONEYChanging(Nullable<global::System.Decimal> value);
        partial void OnMONEYChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OTHER_ACCOUNT
        {
            get
            {
                return _OTHER_ACCOUNT;
            }
            set
            {
                OnOTHER_ACCOUNTChanging(value);
                ReportPropertyChanging("OTHER_ACCOUNT");
                _OTHER_ACCOUNT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OTHER_ACCOUNT");
                OnOTHER_ACCOUNTChanged();
            }
        }
        private global::System.String _OTHER_ACCOUNT;
        partial void OnOTHER_ACCOUNTChanging(global::System.String value);
        partial void OnOTHER_ACCOUNTChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OTHER_ACCOUNT_NAME
        {
            get
            {
                return _OTHER_ACCOUNT_NAME;
            }
            set
            {
                OnOTHER_ACCOUNT_NAMEChanging(value);
                ReportPropertyChanging("OTHER_ACCOUNT_NAME");
                _OTHER_ACCOUNT_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OTHER_ACCOUNT_NAME");
                OnOTHER_ACCOUNT_NAMEChanged();
            }
        }
        private global::System.String _OTHER_ACCOUNT_NAME;
        partial void OnOTHER_ACCOUNT_NAMEChanging(global::System.String value);
        partial void OnOTHER_ACCOUNT_NAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ORDERS
        {
            get
            {
                return _ORDERS;
            }
            set
            {
                OnORDERSChanging(value);
                ReportPropertyChanging("ORDERS");
                _ORDERS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ORDERS");
                OnORDERSChanged();
            }
        }
        private global::System.String _ORDERS;
        partial void OnORDERSChanging(global::System.String value);
        partial void OnORDERSChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RETURN_CODE
        {
            get
            {
                return _RETURN_CODE;
            }
            set
            {
                OnRETURN_CODEChanging(value);
                ReportPropertyChanging("RETURN_CODE");
                _RETURN_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RETURN_CODE");
                OnRETURN_CODEChanged();
            }
        }
        private global::System.String _RETURN_CODE;
        partial void OnRETURN_CODEChanging(global::System.String value);
        partial void OnRETURN_CODEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RETURN_MSG
        {
            get
            {
                return _RETURN_MSG;
            }
            set
            {
                OnRETURN_MSGChanging(value);
                ReportPropertyChanging("RETURN_MSG");
                _RETURN_MSG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RETURN_MSG");
                OnRETURN_MSGChanged();
            }
        }
        private global::System.String _RETURN_MSG;
        partial void OnRETURN_MSGChanging(global::System.String value);
        partial void OnRETURN_MSGChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ISMATCH
        {
            get
            {
                return _ISMATCH;
            }
            set
            {
                OnISMATCHChanging(value);
                ReportPropertyChanging("ISMATCH");
                _ISMATCH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISMATCH");
                OnISMATCHChanged();
            }
        }
        private Nullable<global::System.Int32> _ISMATCH;
        partial void OnISMATCHChanging(Nullable<global::System.Int32> value);
        partial void OnISMATCHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATETIME
        {
            get
            {
                return _CREATETIME;
            }
            set
            {
                OnCREATETIMEChanging(value);
                ReportPropertyChanging("CREATETIME");
                _CREATETIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATETIME");
                OnCREATETIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATETIME;
        partial void OnCREATETIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATETIMEChanged();

        #endregion
    
    }

    #endregion
    
}
