//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace PM.TaskBiz.NetBankTask.ORM
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class Netbank_IntegratedEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“Netbank_IntegratedEntities”部分中的连接字符串初始化新 Netbank_IntegratedEntities 对象。
        /// </summary>
        public Netbank_IntegratedEntities() : base("name=Netbank_IntegratedEntities", "Netbank_IntegratedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Netbank_IntegratedEntities 对象。
        /// </summary>
        public Netbank_IntegratedEntities(string connectionString) : base(connectionString, "Netbank_IntegratedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Netbank_IntegratedEntities 对象。
        /// </summary>
        public Netbank_IntegratedEntities(EntityConnection connection) : base(connection, "Netbank_IntegratedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_ZTB_MoneyPayment> T_ZTB_MoneyPayment
        {
            get
            {
                if ((_T_ZTB_MoneyPayment == null))
                {
                    _T_ZTB_MoneyPayment = base.CreateObjectSet<T_ZTB_MoneyPayment>("T_ZTB_MoneyPayment");
                }
                return _T_ZTB_MoneyPayment;
            }
        }
        private ObjectSet<T_ZTB_MoneyPayment> _T_ZTB_MoneyPayment;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_NetBankAccountQuery> T_NetBankAccountQuery
        {
            get
            {
                if ((_T_NetBankAccountQuery == null))
                {
                    _T_NetBankAccountQuery = base.CreateObjectSet<T_NetBankAccountQuery>("T_NetBankAccountQuery");
                }
                return _T_NetBankAccountQuery;
            }
        }
        private ObjectSet<T_NetBankAccountQuery> _T_NetBankAccountQuery;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 T_ZTB_MoneyPayment EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_ZTB_MoneyPayment(T_ZTB_MoneyPayment t_ZTB_MoneyPayment)
        {
            base.AddObject("T_ZTB_MoneyPayment", t_ZTB_MoneyPayment);
        }
    
        /// <summary>
        /// 用于向 T_NetBankAccountQuery EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_NetBankAccountQuery(T_NetBankAccountQuery t_NetBankAccountQuery)
        {
            base.AddObject("T_NetBankAccountQuery", t_NetBankAccountQuery);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NetBank_IntegratedModel", Name="T_NetBankAccountQuery")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_NetBankAccountQuery : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_NetBankAccountQuery 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static T_NetBankAccountQuery CreateT_NetBankAccountQuery(global::System.String id)
        {
            T_NetBankAccountQuery t_NetBankAccountQuery = new T_NetBankAccountQuery();
            t_NetBankAccountQuery.ID = id;
            return t_NetBankAccountQuery;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TxType
        {
            get
            {
                return _TxType;
            }
            set
            {
                OnTxTypeChanging(value);
                ReportPropertyChanging("TxType");
                _TxType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TxType");
                OnTxTypeChanged();
            }
        }
        private global::System.String _TxType;
        partial void OnTxTypeChanging(global::System.String value);
        partial void OnTxTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TxSn
        {
            get
            {
                return _TxSn;
            }
            set
            {
                OnTxSnChanging(value);
                ReportPropertyChanging("TxSn");
                _TxSn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TxSn");
                OnTxSnChanged();
            }
        }
        private global::System.String _TxSn;
        partial void OnTxSnChanging(global::System.String value);
        partial void OnTxSnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TxAmount
        {
            get
            {
                return _TxAmount;
            }
            set
            {
                OnTxAmountChanging(value);
                ReportPropertyChanging("TxAmount");
                _TxAmount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TxAmount");
                OnTxAmountChanged();
            }
        }
        private global::System.String _TxAmount;
        partial void OnTxAmountChanging(global::System.String value);
        partial void OnTxAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InstitutionAmount
        {
            get
            {
                return _InstitutionAmount;
            }
            set
            {
                OnInstitutionAmountChanging(value);
                ReportPropertyChanging("InstitutionAmount");
                _InstitutionAmount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InstitutionAmount");
                OnInstitutionAmountChanged();
            }
        }
        private global::System.String _InstitutionAmount;
        partial void OnInstitutionAmountChanging(global::System.String value);
        partial void OnInstitutionAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaymentAmount
        {
            get
            {
                return _PaymentAmount;
            }
            set
            {
                OnPaymentAmountChanging(value);
                ReportPropertyChanging("PaymentAmount");
                _PaymentAmount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaymentAmount");
                OnPaymentAmountChanged();
            }
        }
        private global::System.String _PaymentAmount;
        partial void OnPaymentAmountChanging(global::System.String value);
        partial void OnPaymentAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InstitutionFee
        {
            get
            {
                return _InstitutionFee;
            }
            set
            {
                OnInstitutionFeeChanging(value);
                ReportPropertyChanging("InstitutionFee");
                _InstitutionFee = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InstitutionFee");
                OnInstitutionFeeChanged();
            }
        }
        private global::System.String _InstitutionFee;
        partial void OnInstitutionFeeChanging(global::System.String value);
        partial void OnInstitutionFeeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BankNotificationTime
        {
            get
            {
                return _BankNotificationTime;
            }
            set
            {
                OnBankNotificationTimeChanging(value);
                ReportPropertyChanging("BankNotificationTime");
                _BankNotificationTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BankNotificationTime");
                OnBankNotificationTimeChanged();
            }
        }
        private global::System.String _BankNotificationTime;
        partial void OnBankNotificationTimeChanging(global::System.String value);
        partial void OnBankNotificationTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SettlementFlag
        {
            get
            {
                return _SettlementFlag;
            }
            set
            {
                OnSettlementFlagChanging(value);
                ReportPropertyChanging("SettlementFlag");
                _SettlementFlag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SettlementFlag");
                OnSettlementFlagChanged();
            }
        }
        private global::System.String _SettlementFlag;
        partial void OnSettlementFlagChanging(global::System.String value);
        partial void OnSettlementFlagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsMatch
        {
            get
            {
                return _IsMatch;
            }
            set
            {
                OnIsMatchChanging(value);
                ReportPropertyChanging("IsMatch");
                _IsMatch = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMatch");
                OnIsMatchChanged();
            }
        }
        private Nullable<global::System.Int32> _IsMatch;
        partial void OnIsMatchChanging(Nullable<global::System.Int32> value);
        partial void OnIsMatchChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Flag
        {
            get
            {
                return _Flag;
            }
            set
            {
                OnFlagChanging(value);
                ReportPropertyChanging("Flag");
                _Flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Flag");
                OnFlagChanged();
            }
        }
        private Nullable<global::System.Int32> _Flag;
        partial void OnFlagChanging(Nullable<global::System.Int32> value);
        partial void OnFlagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTm
        {
            get
            {
                return _CreateTm;
            }
            set
            {
                OnCreateTmChanging(value);
                ReportPropertyChanging("CreateTm");
                _CreateTm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTm");
                OnCreateTmChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTm;
        partial void OnCreateTmChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTmChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NetBank_IntegratedModel", Name="T_ZTB_MoneyPayment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_ZTB_MoneyPayment : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_ZTB_MoneyPayment 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static T_ZTB_MoneyPayment CreateT_ZTB_MoneyPayment(global::System.Guid id)
        {
            T_ZTB_MoneyPayment t_ZTB_MoneyPayment = new T_ZTB_MoneyPayment();
            t_ZTB_MoneyPayment.Id = id;
            return t_ZTB_MoneyPayment;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProSectionID
        {
            get
            {
                return _ProSectionID;
            }
            set
            {
                OnProSectionIDChanging(value);
                ReportPropertyChanging("ProSectionID");
                _ProSectionID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProSectionID");
                OnProSectionIDChanged();
            }
        }
        private global::System.String _ProSectionID;
        partial void OnProSectionIDChanging(global::System.String value);
        partial void OnProSectionIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProSectionName
        {
            get
            {
                return _ProSectionName;
            }
            set
            {
                OnProSectionNameChanging(value);
                ReportPropertyChanging("ProSectionName");
                _ProSectionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProSectionName");
                OnProSectionNameChanged();
            }
        }
        private global::System.String _ProSectionName;
        partial void OnProSectionNameChanging(global::System.String value);
        partial void OnProSectionNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProSectionCode
        {
            get
            {
                return _ProSectionCode;
            }
            set
            {
                OnProSectionCodeChanging(value);
                ReportPropertyChanging("ProSectionCode");
                _ProSectionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProSectionCode");
                OnProSectionCodeChanged();
            }
        }
        private global::System.String _ProSectionCode;
        partial void OnProSectionCodeChanging(global::System.String value);
        partial void OnProSectionCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PayTime
        {
            get
            {
                return _PayTime;
            }
            set
            {
                OnPayTimeChanging(value);
                ReportPropertyChanging("PayTime");
                _PayTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayTime");
                OnPayTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PayTime;
        partial void OnPayTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPayTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PayMoney
        {
            get
            {
                return _PayMoney;
            }
            set
            {
                OnPayMoneyChanging(value);
                ReportPropertyChanging("PayMoney");
                _PayMoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayMoney");
                OnPayMoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _PayMoney;
        partial void OnPayMoneyChanging(Nullable<global::System.Decimal> value);
        partial void OnPayMoneyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayType
        {
            get
            {
                return _PayType;
            }
            set
            {
                OnPayTypeChanging(value);
                ReportPropertyChanging("PayType");
                _PayType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayType");
                OnPayTypeChanged();
            }
        }
        private global::System.String _PayType;
        partial void OnPayTypeChanging(global::System.String value);
        partial void OnPayTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardNum
        {
            get
            {
                return _CardNum;
            }
            set
            {
                OnCardNumChanging(value);
                ReportPropertyChanging("CardNum");
                _CardNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardNum");
                OnCardNumChanged();
            }
        }
        private global::System.String _CardNum;
        partial void OnCardNumChanging(global::System.String value);
        partial void OnCardNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsCheck
        {
            get
            {
                return _IsCheck;
            }
            set
            {
                OnIsCheckChanging(value);
                ReportPropertyChanging("IsCheck");
                _IsCheck = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCheck");
                OnIsCheckChanged();
            }
        }
        private Nullable<global::System.Int32> _IsCheck;
        partial void OnIsCheckChanging(Nullable<global::System.Int32> value);
        partial void OnIsCheckChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReturnUserId
        {
            get
            {
                return _ReturnUserId;
            }
            set
            {
                OnReturnUserIdChanging(value);
                ReportPropertyChanging("ReturnUserId");
                _ReturnUserId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReturnUserId");
                OnReturnUserIdChanged();
            }
        }
        private global::System.String _ReturnUserId;
        partial void OnReturnUserIdChanging(global::System.String value);
        partial void OnReturnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReTurnUserName
        {
            get
            {
                return _ReTurnUserName;
            }
            set
            {
                OnReTurnUserNameChanging(value);
                ReportPropertyChanging("ReTurnUserName");
                _ReTurnUserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReTurnUserName");
                OnReTurnUserNameChanged();
            }
        }
        private global::System.String _ReTurnUserName;
        partial void OnReTurnUserNameChanging(global::System.String value);
        partial void OnReTurnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReturnTime
        {
            get
            {
                return _ReturnTime;
            }
            set
            {
                OnReturnTimeChanging(value);
                ReportPropertyChanging("ReturnTime");
                _ReturnTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnTime");
                OnReturnTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReturnTime;
        partial void OnReturnTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnReturnTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReturnWindow
        {
            get
            {
                return _ReturnWindow;
            }
            set
            {
                OnReturnWindowChanging(value);
                ReportPropertyChanging("ReturnWindow");
                _ReturnWindow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReturnWindow");
                OnReturnWindowChanged();
            }
        }
        private global::System.String _ReturnWindow;
        partial void OnReturnWindowChanging(global::System.String value);
        partial void OnReturnWindowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReturnPhone
        {
            get
            {
                return _ReturnPhone;
            }
            set
            {
                OnReturnPhoneChanging(value);
                ReportPropertyChanging("ReturnPhone");
                _ReturnPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReturnPhone");
                OnReturnPhoneChanged();
            }
        }
        private global::System.String _ReturnPhone;
        partial void OnReturnPhoneChanging(global::System.String value);
        partial void OnReturnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ReturnYingGaiMon
        {
            get
            {
                return _ReturnYingGaiMon;
            }
            set
            {
                OnReturnYingGaiMonChanging(value);
                ReportPropertyChanging("ReturnYingGaiMon");
                _ReturnYingGaiMon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnYingGaiMon");
                OnReturnYingGaiMonChanged();
            }
        }
        private Nullable<global::System.Decimal> _ReturnYingGaiMon;
        partial void OnReturnYingGaiMonChanging(Nullable<global::System.Decimal> value);
        partial void OnReturnYingGaiMonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ReturnShiJiMon
        {
            get
            {
                return _ReturnShiJiMon;
            }
            set
            {
                OnReturnShiJiMonChanging(value);
                ReportPropertyChanging("ReturnShiJiMon");
                _ReturnShiJiMon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnShiJiMon");
                OnReturnShiJiMonChanged();
            }
        }
        private Nullable<global::System.Decimal> _ReturnShiJiMon;
        partial void OnReturnShiJiMonChanging(Nullable<global::System.Decimal> value);
        partial void OnReturnShiJiMonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReturnBaoHanYouXiaoQi
        {
            get
            {
                return _ReturnBaoHanYouXiaoQi;
            }
            set
            {
                OnReturnBaoHanYouXiaoQiChanging(value);
                ReportPropertyChanging("ReturnBaoHanYouXiaoQi");
                _ReturnBaoHanYouXiaoQi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnBaoHanYouXiaoQi");
                OnReturnBaoHanYouXiaoQiChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReturnBaoHanYouXiaoQi;
        partial void OnReturnBaoHanYouXiaoQiChanging(Nullable<global::System.DateTime> value);
        partial void OnReturnBaoHanYouXiaoQiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReturnBaoHanBank
        {
            get
            {
                return _ReturnBaoHanBank;
            }
            set
            {
                OnReturnBaoHanBankChanging(value);
                ReportPropertyChanging("ReturnBaoHanBank");
                _ReturnBaoHanBank = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReturnBaoHanBank");
                OnReturnBaoHanBankChanged();
            }
        }
        private global::System.String _ReturnBaoHanBank;
        partial void OnReturnBaoHanBankChanging(global::System.String value);
        partial void OnReturnBaoHanBankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReturnBaoHanNum
        {
            get
            {
                return _ReturnBaoHanNum;
            }
            set
            {
                OnReturnBaoHanNumChanging(value);
                ReportPropertyChanging("ReturnBaoHanNum");
                _ReturnBaoHanNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReturnBaoHanNum");
                OnReturnBaoHanNumChanged();
            }
        }
        private global::System.String _ReturnBaoHanNum;
        partial void OnReturnBaoHanNumChanging(global::System.String value);
        partial void OnReturnBaoHanNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsReturn
        {
            get
            {
                return _IsReturn;
            }
            set
            {
                OnIsReturnChanging(value);
                ReportPropertyChanging("IsReturn");
                _IsReturn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsReturn");
                OnIsReturnChanged();
            }
        }
        private Nullable<global::System.Int32> _IsReturn;
        partial void OnIsReturnChanging(Nullable<global::System.Int32> value);
        partial void OnIsReturnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitId
        {
            get
            {
                return _UnitId;
            }
            set
            {
                OnUnitIdChanging(value);
                ReportPropertyChanging("UnitId");
                _UnitId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitId");
                OnUnitIdChanged();
            }
        }
        private global::System.String _UnitId;
        partial void OnUnitIdChanging(global::System.String value);
        partial void OnUnitIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitName
        {
            get
            {
                return _UnitName;
            }
            set
            {
                OnUnitNameChanging(value);
                ReportPropertyChanging("UnitName");
                _UnitName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitName");
                OnUnitNameChanged();
            }
        }
        private global::System.String _UnitName;
        partial void OnUnitNameChanging(global::System.String value);
        partial void OnUnitNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitCode
        {
            get
            {
                return _UnitCode;
            }
            set
            {
                OnUnitCodeChanging(value);
                ReportPropertyChanging("UnitCode");
                _UnitCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitCode");
                OnUnitCodeChanged();
            }
        }
        private global::System.String _UnitCode;
        partial void OnUnitCodeChanging(global::System.String value);
        partial void OnUnitCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BankCardNum
        {
            get
            {
                return _BankCardNum;
            }
            set
            {
                OnBankCardNumChanging(value);
                ReportPropertyChanging("BankCardNum");
                _BankCardNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BankCardNum");
                OnBankCardNumChanged();
            }
        }
        private global::System.String _BankCardNum;
        partial void OnBankCardNumChanging(global::System.String value);
        partial void OnBankCardNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BankName
        {
            get
            {
                return _BankName;
            }
            set
            {
                OnBankNameChanging(value);
                ReportPropertyChanging("BankName");
                _BankName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BankName");
                OnBankNameChanged();
            }
        }
        private global::System.String _BankName;
        partial void OnBankNameChanging(global::System.String value);
        partial void OnBankNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CaseID
        {
            get
            {
                return _CaseID;
            }
            set
            {
                OnCaseIDChanging(value);
                ReportPropertyChanging("CaseID");
                _CaseID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CaseID");
                OnCaseIDChanged();
            }
        }
        private global::System.String _CaseID;
        partial void OnCaseIDChanging(global::System.String value);
        partial void OnCaseIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProName
        {
            get
            {
                return _ProName;
            }
            set
            {
                OnProNameChanging(value);
                ReportPropertyChanging("ProName");
                _ProName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProName");
                OnProNameChanged();
            }
        }
        private global::System.String _ProName;
        partial void OnProNameChanging(global::System.String value);
        partial void OnProNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProCode
        {
            get
            {
                return _ProCode;
            }
            set
            {
                OnProCodeChanging(value);
                ReportPropertyChanging("ProCode");
                _ProCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProCode");
                OnProCodeChanged();
            }
        }
        private global::System.String _ProCode;
        partial void OnProCodeChanging(global::System.String value);
        partial void OnProCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PayPage
        {
            get
            {
                return _PayPage;
            }
            set
            {
                OnPayPageChanging(value);
                ReportPropertyChanging("PayPage");
                _PayPage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayPage");
                OnPayPageChanged();
            }
        }
        private Nullable<global::System.Int32> _PayPage;
        partial void OnPayPageChanging(Nullable<global::System.Int32> value);
        partial void OnPayPageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayPageText
        {
            get
            {
                return _PayPageText;
            }
            set
            {
                OnPayPageTextChanging(value);
                ReportPropertyChanging("PayPageText");
                _PayPageText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayPageText");
                OnPayPageTextChanged();
            }
        }
        private global::System.String _PayPageText;
        partial void OnPayPageTextChanging(global::System.String value);
        partial void OnPayPageTextChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromSystem
        {
            get
            {
                return _FromSystem;
            }
            set
            {
                OnFromSystemChanging(value);
                ReportPropertyChanging("FromSystem");
                _FromSystem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FromSystem");
                OnFromSystemChanged();
            }
        }
        private global::System.String _FromSystem;
        partial void OnFromSystemChanging(global::System.String value);
        partial void OnFromSystemChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayID
        {
            get
            {
                return _PayID;
            }
            set
            {
                OnPayIDChanging(value);
                ReportPropertyChanging("PayID");
                _PayID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayID");
                OnPayIDChanged();
            }
        }
        private global::System.String _PayID;
        partial void OnPayIDChanging(global::System.String value);
        partial void OnPayIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Out_trade_no
        {
            get
            {
                return _Out_trade_no;
            }
            set
            {
                OnOut_trade_noChanging(value);
                ReportPropertyChanging("Out_trade_no");
                _Out_trade_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Out_trade_no");
                OnOut_trade_noChanged();
            }
        }
        private global::System.String _Out_trade_no;
        partial void OnOut_trade_noChanging(global::System.String value);
        partial void OnOut_trade_noChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> QueRenRuZhangTime
        {
            get
            {
                return _QueRenRuZhangTime;
            }
            set
            {
                OnQueRenRuZhangTimeChanging(value);
                ReportPropertyChanging("QueRenRuZhangTime");
                _QueRenRuZhangTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QueRenRuZhangTime");
                OnQueRenRuZhangTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _QueRenRuZhangTime;
        partial void OnQueRenRuZhangTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnQueRenRuZhangTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QueRenRuZhangPerson
        {
            get
            {
                return _QueRenRuZhangPerson;
            }
            set
            {
                OnQueRenRuZhangPersonChanging(value);
                ReportPropertyChanging("QueRenRuZhangPerson");
                _QueRenRuZhangPerson = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QueRenRuZhangPerson");
                OnQueRenRuZhangPersonChanged();
            }
        }
        private global::System.String _QueRenRuZhangPerson;
        partial void OnQueRenRuZhangPersonChanging(global::System.String value);
        partial void OnQueRenRuZhangPersonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayLinkPerson
        {
            get
            {
                return _PayLinkPerson;
            }
            set
            {
                OnPayLinkPersonChanging(value);
                ReportPropertyChanging("PayLinkPerson");
                _PayLinkPerson = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayLinkPerson");
                OnPayLinkPersonChanged();
            }
        }
        private global::System.String _PayLinkPerson;
        partial void OnPayLinkPersonChanging(global::System.String value);
        partial void OnPayLinkPersonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayLinkPersonTel
        {
            get
            {
                return _PayLinkPersonTel;
            }
            set
            {
                OnPayLinkPersonTelChanging(value);
                ReportPropertyChanging("PayLinkPersonTel");
                _PayLinkPersonTel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayLinkPersonTel");
                OnPayLinkPersonTelChanged();
            }
        }
        private global::System.String _PayLinkPersonTel;
        partial void OnPayLinkPersonTelChanging(global::System.String value);
        partial void OnPayLinkPersonTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayLinkPersonMobileTel
        {
            get
            {
                return _PayLinkPersonMobileTel;
            }
            set
            {
                OnPayLinkPersonMobileTelChanging(value);
                ReportPropertyChanging("PayLinkPersonMobileTel");
                _PayLinkPersonMobileTel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayLinkPersonMobileTel");
                OnPayLinkPersonMobileTelChanged();
            }
        }
        private global::System.String _PayLinkPersonMobileTel;
        partial void OnPayLinkPersonMobileTelChanging(global::System.String value);
        partial void OnPayLinkPersonMobileTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsWinBid
        {
            get
            {
                return _IsWinBid;
            }
            set
            {
                OnIsWinBidChanging(value);
                ReportPropertyChanging("IsWinBid");
                _IsWinBid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsWinBid");
                OnIsWinBidChanged();
            }
        }
        private Nullable<global::System.Int32> _IsWinBid;
        partial void OnIsWinBidChanging(Nullable<global::System.Int32> value);
        partial void OnIsWinBidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TouBiaoEndTime
        {
            get
            {
                return _TouBiaoEndTime;
            }
            set
            {
                OnTouBiaoEndTimeChanging(value);
                ReportPropertyChanging("TouBiaoEndTime");
                _TouBiaoEndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TouBiaoEndTime");
                OnTouBiaoEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _TouBiaoEndTime;
        partial void OnTouBiaoEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnTouBiaoEndTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JiaoFeiBiLv
        {
            get
            {
                return _JiaoFeiBiLv;
            }
            set
            {
                OnJiaoFeiBiLvChanging(value);
                ReportPropertyChanging("JiaoFeiBiLv");
                _JiaoFeiBiLv = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JiaoFeiBiLv");
                OnJiaoFeiBiLvChanged();
            }
        }
        private global::System.String _JiaoFeiBiLv;
        partial void OnJiaoFeiBiLvChanging(global::System.String value);
        partial void OnJiaoFeiBiLvChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contentv
        {
            get
            {
                return _Contentv;
            }
            set
            {
                OnContentvChanging(value);
                ReportPropertyChanging("Contentv");
                _Contentv = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contentv");
                OnContentvChanged();
            }
        }
        private global::System.String _Contentv;
        partial void OnContentvChanging(global::System.String value);
        partial void OnContentvChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InvoiceTitle
        {
            get
            {
                return _InvoiceTitle;
            }
            set
            {
                OnInvoiceTitleChanging(value);
                ReportPropertyChanging("InvoiceTitle");
                _InvoiceTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InvoiceTitle");
                OnInvoiceTitleChanged();
            }
        }
        private global::System.String _InvoiceTitle;
        partial void OnInvoiceTitleChanging(global::System.String value);
        partial void OnInvoiceTitleChanged();

        #endregion

    
    }

    #endregion

    
}
