//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace PM.TaskBiz.HuangMeiPostlTask.ORM
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class GovPublic_jinhuaEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“GovPublic_jinhuaEntities”部分中的连接字符串初始化新 GovPublic_jinhuaEntities 对象。
        /// </summary>
        public GovPublic_jinhuaEntities() : base("name=GovPublic_jinhuaEntities", "GovPublic_jinhuaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 GovPublic_jinhuaEntities 对象。
        /// </summary>
        public GovPublic_jinhuaEntities(string connectionString) : base(connectionString, "GovPublic_jinhuaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 GovPublic_jinhuaEntities 对象。
        /// </summary>
        public GovPublic_jinhuaEntities(EntityConnection connection) : base(connection, "GovPublic_jinhuaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_HMPostal> T_HMPostal
        {
            get
            {
                if ((_T_HMPostal == null))
                {
                    _T_HMPostal = base.CreateObjectSet<T_HMPostal>("T_HMPostal");
                }
                return _T_HMPostal;
            }
        }
        private ObjectSet<T_HMPostal> _T_HMPostal;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 T_HMPostal EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_HMPostal(T_HMPostal t_HMPostal)
        {
            base.AddObject("T_HMPostal", t_HMPostal);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HM", Name="T_HMPostal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_HMPostal : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_HMPostal 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static T_HMPostal CreateT_HMPostal(global::System.String id)
        {
            T_HMPostal t_HMPostal = new T_HMPostal();
            t_HMPostal.ID = id;
            return t_HMPostal;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountNo
        {
            get
            {
                return _AccountNo;
            }
            set
            {
                OnAccountNoChanging(value);
                ReportPropertyChanging("AccountNo");
                _AccountNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountNo");
                OnAccountNoChanged();
            }
        }
        private global::System.String _AccountNo;
        partial void OnAccountNoChanging(global::System.String value);
        partial void OnAccountNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TradeDate
        {
            get
            {
                return _TradeDate;
            }
            set
            {
                OnTradeDateChanging(value);
                ReportPropertyChanging("TradeDate");
                _TradeDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TradeDate");
                OnTradeDateChanged();
            }
        }
        private global::System.String _TradeDate;
        partial void OnTradeDateChanging(global::System.String value);
        partial void OnTradeDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TradeSerialNumber
        {
            get
            {
                return _TradeSerialNumber;
            }
            set
            {
                OnTradeSerialNumberChanging(value);
                ReportPropertyChanging("TradeSerialNumber");
                _TradeSerialNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TradeSerialNumber");
                OnTradeSerialNumberChanged();
            }
        }
        private global::System.String _TradeSerialNumber;
        partial void OnTradeSerialNumberChanging(global::System.String value);
        partial void OnTradeSerialNumberChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProofKind
        {
            get
            {
                return _ProofKind;
            }
            set
            {
                OnProofKindChanging(value);
                ReportPropertyChanging("ProofKind");
                _ProofKind = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProofKind");
                OnProofKindChanged();
            }
        }
        private global::System.String _ProofKind;
        partial void OnProofKindChanging(global::System.String value);
        partial void OnProofKindChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProofNum
        {
            get
            {
                return _ProofNum;
            }
            set
            {
                OnProofNumChanging(value);
                ReportPropertyChanging("ProofNum");
                _ProofNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProofNum");
                OnProofNumChanged();
            }
        }
        private global::System.String _ProofNum;
        partial void OnProofNumChanging(global::System.String value);
        partial void OnProofNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoanMark
        {
            get
            {
                return _LoanMark;
            }
            set
            {
                OnLoanMarkChanging(value);
                ReportPropertyChanging("LoanMark");
                _LoanMark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LoanMark");
                OnLoanMarkChanged();
            }
        }
        private global::System.String _LoanMark;
        partial void OnLoanMarkChanging(global::System.String value);
        partial void OnLoanMarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RemainAmount
        {
            get
            {
                return _RemainAmount;
            }
            set
            {
                OnRemainAmountChanging(value);
                ReportPropertyChanging("RemainAmount");
                _RemainAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RemainAmount");
                OnRemainAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _RemainAmount;
        partial void OnRemainAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnRemainAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Oprationer
        {
            get
            {
                return _Oprationer;
            }
            set
            {
                OnOprationerChanging(value);
                ReportPropertyChanging("Oprationer");
                _Oprationer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Oprationer");
                OnOprationerChanged();
            }
        }
        private global::System.String _Oprationer;
        partial void OnOprationerChanging(global::System.String value);
        partial void OnOprationerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Checker
        {
            get
            {
                return _Checker;
            }
            set
            {
                OnCheckerChanging(value);
                ReportPropertyChanging("Checker");
                _Checker = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Checker");
                OnCheckerChanged();
            }
        }
        private global::System.String _Checker;
        partial void OnCheckerChanging(global::System.String value);
        partial void OnCheckerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Authorizer
        {
            get
            {
                return _Authorizer;
            }
            set
            {
                OnAuthorizerChanging(value);
                ReportPropertyChanging("Authorizer");
                _Authorizer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Authorizer");
                OnAuthorizerChanged();
            }
        }
        private global::System.String _Authorizer;
        partial void OnAuthorizerChanging(global::System.String value);
        partial void OnAuthorizerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CounterpartAccountNo
        {
            get
            {
                return _CounterpartAccountNo;
            }
            set
            {
                OnCounterpartAccountNoChanging(value);
                ReportPropertyChanging("CounterpartAccountNo");
                _CounterpartAccountNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CounterpartAccountNo");
                OnCounterpartAccountNoChanged();
            }
        }
        private global::System.String _CounterpartAccountNo;
        partial void OnCounterpartAccountNoChanging(global::System.String value);
        partial void OnCounterpartAccountNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CounterpartAccountName
        {
            get
            {
                return _CounterpartAccountName;
            }
            set
            {
                OnCounterpartAccountNameChanging(value);
                ReportPropertyChanging("CounterpartAccountName");
                _CounterpartAccountName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CounterpartAccountName");
                OnCounterpartAccountNameChanged();
            }
        }
        private global::System.String _CounterpartAccountName;
        partial void OnCounterpartAccountNameChanging(global::System.String value);
        partial void OnCounterpartAccountNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TradeWay
        {
            get
            {
                return _TradeWay;
            }
            set
            {
                OnTradeWayChanging(value);
                ReportPropertyChanging("TradeWay");
                _TradeWay = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TradeWay");
                OnTradeWayChanged();
            }
        }
        private global::System.String _TradeWay;
        partial void OnTradeWayChanging(global::System.String value);
        partial void OnTradeWayChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TradeNo
        {
            get
            {
                return _TradeNo;
            }
            set
            {
                OnTradeNoChanging(value);
                ReportPropertyChanging("TradeNo");
                _TradeNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TradeNo");
                OnTradeNoChanged();
            }
        }
        private global::System.String _TradeNo;
        partial void OnTradeNoChanging(global::System.String value);
        partial void OnTradeNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private global::System.String _TimeStamp;
        partial void OnTimeStampChanging(global::System.String value);
        partial void OnTimeStampChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentAccName
        {
            get
            {
                return _DepartmentAccName;
            }
            set
            {
                OnDepartmentAccNameChanging(value);
                ReportPropertyChanging("DepartmentAccName");
                _DepartmentAccName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentAccName");
                OnDepartmentAccNameChanged();
            }
        }
        private global::System.String _DepartmentAccName;
        partial void OnDepartmentAccNameChanging(global::System.String value);
        partial void OnDepartmentAccNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Match
        {
            get
            {
                return _Match;
            }
            set
            {
                OnMatchChanging(value);
                ReportPropertyChanging("Match");
                _Match = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Match");
                OnMatchChanged();
            }
        }
        private Nullable<global::System.Int32> _Match;
        partial void OnMatchChanging(Nullable<global::System.Int32> value);
        partial void OnMatchChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Flag
        {
            get
            {
                return _Flag;
            }
            set
            {
                OnFlagChanging(value);
                ReportPropertyChanging("Flag");
                _Flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Flag");
                OnFlagChanged();
            }
        }
        private Nullable<global::System.Int32> _Flag;
        partial void OnFlagChanging(Nullable<global::System.Int32> value);
        partial void OnFlagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTm
        {
            get
            {
                return _CreateTm;
            }
            set
            {
                OnCreateTmChanging(value);
                ReportPropertyChanging("CreateTm");
                _CreateTm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTm");
                OnCreateTmChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTm;
        partial void OnCreateTmChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTmChanged();

        #endregion

    
    }

    #endregion

    
}
