//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace PM.TaskBiz.JSABOCTask.ORM
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class GovPmBidOnline_BusinessJSEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“GovPmBidOnline_BusinessJSEntities”部分中的连接字符串初始化新 GovPmBidOnline_BusinessJSEntities 对象。
        /// </summary>
        public GovPmBidOnline_BusinessJSEntities() : base("name=GovPmBidOnline_BusinessJSEntities", "GovPmBidOnline_BusinessJSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 GovPmBidOnline_BusinessJSEntities 对象。
        /// </summary>
        public GovPmBidOnline_BusinessJSEntities(string connectionString) : base(connectionString, "GovPmBidOnline_BusinessJSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 GovPmBidOnline_BusinessJSEntities 对象。
        /// </summary>
        public GovPmBidOnline_BusinessJSEntities(EntityConnection connection) : base(connection, "GovPmBidOnline_BusinessJSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_ZTB_BidMoneyPayReturn> T_ZTB_BidMoneyPayReturn
        {
            get
            {
                if ((_T_ZTB_BidMoneyPayReturn == null))
                {
                    _T_ZTB_BidMoneyPayReturn = base.CreateObjectSet<T_ZTB_BidMoneyPayReturn>("T_ZTB_BidMoneyPayReturn");
                }
                return _T_ZTB_BidMoneyPayReturn;
            }
        }
        private ObjectSet<T_ZTB_BidMoneyPayReturn> _T_ZTB_BidMoneyPayReturn;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_JSABOC> T_JSABOC
        {
            get
            {
                if ((_T_JSABOC == null))
                {
                    _T_JSABOC = base.CreateObjectSet<T_JSABOC>("T_JSABOC");
                }
                return _T_JSABOC;
            }
        }
        private ObjectSet<T_JSABOC> _T_JSABOC;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 T_ZTB_BidMoneyPayReturn EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_ZTB_BidMoneyPayReturn(T_ZTB_BidMoneyPayReturn t_ZTB_BidMoneyPayReturn)
        {
            base.AddObject("T_ZTB_BidMoneyPayReturn", t_ZTB_BidMoneyPayReturn);
        }
    
        /// <summary>
        /// 用于向 T_JSABOC EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_JSABOC(T_JSABOC t_JSABOC)
        {
            base.AddObject("T_JSABOC", t_JSABOC);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JSModel", Name="T_JSABOC")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_JSABOC : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_JSABOC 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static T_JSABOC CreateT_JSABOC(global::System.String id)
        {
            T_JSABOC t_JSABOC = new T_JSABOC();
            t_JSABOC.ID = id;
            return t_JSABOC;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TradeCode
        {
            get
            {
                return _TradeCode;
            }
            set
            {
                OnTradeCodeChanging(value);
                ReportPropertyChanging("TradeCode");
                _TradeCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TradeCode");
                OnTradeCodeChanged();
            }
        }
        private global::System.String _TradeCode;
        partial void OnTradeCodeChanging(global::System.String value);
        partial void OnTradeCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TradeStructNum
        {
            get
            {
                return _TradeStructNum;
            }
            set
            {
                OnTradeStructNumChanging(value);
                ReportPropertyChanging("TradeStructNum");
                _TradeStructNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TradeStructNum");
                OnTradeStructNumChanged();
            }
        }
        private global::System.String _TradeStructNum;
        partial void OnTradeStructNumChanging(global::System.String value);
        partial void OnTradeStructNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReturneCode
        {
            get
            {
                return _ReturneCode;
            }
            set
            {
                OnReturneCodeChanging(value);
                ReportPropertyChanging("ReturneCode");
                _ReturneCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReturneCode");
                OnReturneCodeChanged();
            }
        }
        private global::System.String _ReturneCode;
        partial void OnReturneCodeChanging(global::System.String value);
        partial void OnReturneCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReturneMsg
        {
            get
            {
                return _ReturneMsg;
            }
            set
            {
                OnReturneMsgChanging(value);
                ReportPropertyChanging("ReturneMsg");
                _ReturneMsg = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReturneMsg");
                OnReturneMsgChanged();
            }
        }
        private global::System.String _ReturneMsg;
        partial void OnReturneMsgChanging(global::System.String value);
        partial void OnReturneMsgChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DetailDataTime
        {
            get
            {
                return _DetailDataTime;
            }
            set
            {
                OnDetailDataTimeChanging(value);
                ReportPropertyChanging("DetailDataTime");
                _DetailDataTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DetailDataTime");
                OnDetailDataTimeChanged();
            }
        }
        private global::System.String _DetailDataTime;
        partial void OnDetailDataTimeChanging(global::System.String value);
        partial void OnDetailDataTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private Nullable<global::System.Int32> _Count;
        partial void OnCountChanging(Nullable<global::System.Int32> value);
        partial void OnCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SectionNo
        {
            get
            {
                return _SectionNo;
            }
            set
            {
                OnSectionNoChanging(value);
                ReportPropertyChanging("SectionNo");
                _SectionNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SectionNo");
                OnSectionNoChanged();
            }
        }
        private global::System.String _SectionNo;
        partial void OnSectionNoChanging(global::System.String value);
        partial void OnSectionNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReceiveAccNo
        {
            get
            {
                return _ReceiveAccNo;
            }
            set
            {
                OnReceiveAccNoChanging(value);
                ReportPropertyChanging("ReceiveAccNo");
                _ReceiveAccNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReceiveAccNo");
                OnReceiveAccNoChanged();
            }
        }
        private global::System.String _ReceiveAccNo;
        partial void OnReceiveAccNoChanging(global::System.String value);
        partial void OnReceiveAccNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReceiveAccDbName
        {
            get
            {
                return _ReceiveAccDbName;
            }
            set
            {
                OnReceiveAccDbNameChanging(value);
                ReportPropertyChanging("ReceiveAccDbName");
                _ReceiveAccDbName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReceiveAccDbName");
                OnReceiveAccDbNameChanged();
            }
        }
        private global::System.String _ReceiveAccDbName;
        partial void OnReceiveAccDbNameChanging(global::System.String value);
        partial void OnReceiveAccDbNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReceiveAccDBBank
        {
            get
            {
                return _ReceiveAccDBBank;
            }
            set
            {
                OnReceiveAccDBBankChanging(value);
                ReportPropertyChanging("ReceiveAccDBBank");
                _ReceiveAccDBBank = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReceiveAccDBBank");
                OnReceiveAccDBBankChanged();
            }
        }
        private global::System.String _ReceiveAccDBBank;
        partial void OnReceiveAccDBBankChanging(global::System.String value);
        partial void OnReceiveAccDBBankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Used
        {
            get
            {
                return _Used;
            }
            set
            {
                OnUsedChanging(value);
                ReportPropertyChanging("Used");
                _Used = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Used");
                OnUsedChanged();
            }
        }
        private global::System.String _Used;
        partial void OnUsedChanging(global::System.String value);
        partial void OnUsedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayAccNo
        {
            get
            {
                return _PayAccNo;
            }
            set
            {
                OnPayAccNoChanging(value);
                ReportPropertyChanging("PayAccNo");
                _PayAccNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayAccNo");
                OnPayAccNoChanged();
            }
        }
        private global::System.String _PayAccNo;
        partial void OnPayAccNoChanging(global::System.String value);
        partial void OnPayAccNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayAccDbName
        {
            get
            {
                return _PayAccDbName;
            }
            set
            {
                OnPayAccDbNameChanging(value);
                ReportPropertyChanging("PayAccDbName");
                _PayAccDbName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayAccDbName");
                OnPayAccDbNameChanged();
            }
        }
        private global::System.String _PayAccDbName;
        partial void OnPayAccDbNameChanging(global::System.String value);
        partial void OnPayAccDbNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayAccDBBank
        {
            get
            {
                return _PayAccDBBank;
            }
            set
            {
                OnPayAccDBBankChanging(value);
                ReportPropertyChanging("PayAccDBBank");
                _PayAccDBBank = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayAccDBBank");
                OnPayAccDBBankChanged();
            }
        }
        private global::System.String _PayAccDBBank;
        partial void OnPayAccDBBankChanging(global::System.String value);
        partial void OnPayAccDBBankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RealAmount
        {
            get
            {
                return _RealAmount;
            }
            set
            {
                OnRealAmountChanging(value);
                ReportPropertyChanging("RealAmount");
                _RealAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RealAmount");
                OnRealAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _RealAmount;
        partial void OnRealAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnRealAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Summary
        {
            get
            {
                return _Summary;
            }
            set
            {
                OnSummaryChanging(value);
                ReportPropertyChanging("Summary");
                _Summary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Summary");
                OnSummaryChanged();
            }
        }
        private global::System.String _Summary;
        partial void OnSummaryChanging(global::System.String value);
        partial void OnSummaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SerialNumber
        {
            get
            {
                return _SerialNumber;
            }
            set
            {
                OnSerialNumberChanging(value);
                ReportPropertyChanging("SerialNumber");
                _SerialNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SerialNumber");
                OnSerialNumberChanged();
            }
        }
        private global::System.String _SerialNumber;
        partial void OnSerialNumberChanging(global::System.String value);
        partial void OnSerialNumberChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderNo
        {
            get
            {
                return _OrderNo;
            }
            set
            {
                OnOrderNoChanging(value);
                ReportPropertyChanging("OrderNo");
                _OrderNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderNo");
                OnOrderNoChanged();
            }
        }
        private global::System.String _OrderNo;
        partial void OnOrderNoChanging(global::System.String value);
        partial void OnOrderNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsAboc
        {
            get
            {
                return _IsAboc;
            }
            set
            {
                OnIsAbocChanging(value);
                ReportPropertyChanging("IsAboc");
                _IsAboc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAboc");
                OnIsAbocChanged();
            }
        }
        private Nullable<global::System.Int32> _IsAboc;
        partial void OnIsAbocChanging(Nullable<global::System.Int32> value);
        partial void OnIsAbocChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsMatch
        {
            get
            {
                return _IsMatch;
            }
            set
            {
                OnIsMatchChanging(value);
                ReportPropertyChanging("IsMatch");
                _IsMatch = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMatch");
                OnIsMatchChanged();
            }
        }
        private Nullable<global::System.Int32> _IsMatch;
        partial void OnIsMatchChanging(Nullable<global::System.Int32> value);
        partial void OnIsMatchChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Flag
        {
            get
            {
                return _Flag;
            }
            set
            {
                OnFlagChanging(value);
                ReportPropertyChanging("Flag");
                _Flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Flag");
                OnFlagChanged();
            }
        }
        private Nullable<global::System.Int32> _Flag;
        partial void OnFlagChanging(Nullable<global::System.Int32> value);
        partial void OnFlagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String accountType
        {
            get
            {
                return _accountType;
            }
            set
            {
                OnaccountTypeChanging(value);
                ReportPropertyChanging("accountType");
                _accountType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("accountType");
                OnaccountTypeChanged();
            }
        }
        private global::System.String _accountType;
        partial void OnaccountTypeChanging(global::System.String value);
        partial void OnaccountTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTm
        {
            get
            {
                return _CreateTm;
            }
            set
            {
                OnCreateTmChanging(value);
                ReportPropertyChanging("CreateTm");
                _CreateTm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTm");
                OnCreateTmChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTm;
        partial void OnCreateTmChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTmChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JSModel", Name="T_ZTB_BidMoneyPayReturn")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_ZTB_BidMoneyPayReturn : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_ZTB_BidMoneyPayReturn 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="autoId">AutoId 属性的初始值。</param>
        public static T_ZTB_BidMoneyPayReturn CreateT_ZTB_BidMoneyPayReturn(global::System.Guid id, global::System.Int32 autoId)
        {
            T_ZTB_BidMoneyPayReturn t_ZTB_BidMoneyPayReturn = new T_ZTB_BidMoneyPayReturn();
            t_ZTB_BidMoneyPayReturn.Id = id;
            t_ZTB_BidMoneyPayReturn.AutoId = autoId;
            return t_ZTB_BidMoneyPayReturn;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CaseId
        {
            get
            {
                return _CaseId;
            }
            set
            {
                OnCaseIdChanging(value);
                ReportPropertyChanging("CaseId");
                _CaseId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CaseId");
                OnCaseIdChanged();
            }
        }
        private Nullable<global::System.Guid> _CaseId;
        partial void OnCaseIdChanging(Nullable<global::System.Guid> value);
        partial void OnCaseIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> BidderId
        {
            get
            {
                return _BidderId;
            }
            set
            {
                OnBidderIdChanging(value);
                ReportPropertyChanging("BidderId");
                _BidderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BidderId");
                OnBidderIdChanged();
            }
        }
        private Nullable<global::System.Guid> _BidderId;
        partial void OnBidderIdChanging(Nullable<global::System.Guid> value);
        partial void OnBidderIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IincurredTime
        {
            get
            {
                return _IincurredTime;
            }
            set
            {
                OnIincurredTimeChanging(value);
                ReportPropertyChanging("IincurredTime");
                _IincurredTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IincurredTime");
                OnIincurredTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _IincurredTime;
        partial void OnIincurredTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnIincurredTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PayTime
        {
            get
            {
                return _PayTime;
            }
            set
            {
                OnPayTimeChanging(value);
                ReportPropertyChanging("PayTime");
                _PayTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayTime");
                OnPayTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PayTime;
        partial void OnPayTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPayTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PayFee
        {
            get
            {
                return _PayFee;
            }
            set
            {
                OnPayFeeChanging(value);
                ReportPropertyChanging("PayFee");
                _PayFee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayFee");
                OnPayFeeChanged();
            }
        }
        private Nullable<global::System.Decimal> _PayFee;
        partial void OnPayFeeChanging(Nullable<global::System.Decimal> value);
        partial void OnPayFeeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PayMoney
        {
            get
            {
                return _PayMoney;
            }
            set
            {
                OnPayMoneyChanging(value);
                ReportPropertyChanging("PayMoney");
                _PayMoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayMoney");
                OnPayMoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _PayMoney;
        partial void OnPayMoneyChanging(Nullable<global::System.Decimal> value);
        partial void OnPayMoneyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayType
        {
            get
            {
                return _PayType;
            }
            set
            {
                OnPayTypeChanging(value);
                ReportPropertyChanging("PayType");
                _PayType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayType");
                OnPayTypeChanged();
            }
        }
        private global::System.String _PayType;
        partial void OnPayTypeChanging(global::System.String value);
        partial void OnPayTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardNum
        {
            get
            {
                return _CardNum;
            }
            set
            {
                OnCardNumChanging(value);
                ReportPropertyChanging("CardNum");
                _CardNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardNum");
                OnCardNumChanged();
            }
        }
        private global::System.String _CardNum;
        partial void OnCardNumChanging(global::System.String value);
        partial void OnCardNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsCheck
        {
            get
            {
                return _IsCheck;
            }
            set
            {
                OnIsCheckChanging(value);
                ReportPropertyChanging("IsCheck");
                _IsCheck = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCheck");
                OnIsCheckChanged();
            }
        }
        private Nullable<global::System.Int32> _IsCheck;
        partial void OnIsCheckChanging(Nullable<global::System.Int32> value);
        partial void OnIsCheckChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ReturnManId
        {
            get
            {
                return _ReturnManId;
            }
            set
            {
                OnReturnManIdChanging(value);
                ReportPropertyChanging("ReturnManId");
                _ReturnManId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnManId");
                OnReturnManIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ReturnManId;
        partial void OnReturnManIdChanging(Nullable<global::System.Guid> value);
        partial void OnReturnManIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReturnTime
        {
            get
            {
                return _ReturnTime;
            }
            set
            {
                OnReturnTimeChanging(value);
                ReportPropertyChanging("ReturnTime");
                _ReturnTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnTime");
                OnReturnTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReturnTime;
        partial void OnReturnTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnReturnTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReturnWindow
        {
            get
            {
                return _ReturnWindow;
            }
            set
            {
                OnReturnWindowChanging(value);
                ReportPropertyChanging("ReturnWindow");
                _ReturnWindow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReturnWindow");
                OnReturnWindowChanged();
            }
        }
        private global::System.String _ReturnWindow;
        partial void OnReturnWindowChanging(global::System.String value);
        partial void OnReturnWindowChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsReturn
        {
            get
            {
                return _IsReturn;
            }
            set
            {
                OnIsReturnChanging(value);
                ReportPropertyChanging("IsReturn");
                _IsReturn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsReturn");
                OnIsReturnChanged();
            }
        }
        private Nullable<global::System.Int32> _IsReturn;
        partial void OnIsReturnChanging(Nullable<global::System.Int32> value);
        partial void OnIsReturnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UnitId
        {
            get
            {
                return _UnitId;
            }
            set
            {
                OnUnitIdChanging(value);
                ReportPropertyChanging("UnitId");
                _UnitId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitId");
                OnUnitIdChanged();
            }
        }
        private Nullable<global::System.Guid> _UnitId;
        partial void OnUnitIdChanging(Nullable<global::System.Guid> value);
        partial void OnUnitIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BankCardNum
        {
            get
            {
                return _BankCardNum;
            }
            set
            {
                OnBankCardNumChanging(value);
                ReportPropertyChanging("BankCardNum");
                _BankCardNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BankCardNum");
                OnBankCardNumChanged();
            }
        }
        private global::System.String _BankCardNum;
        partial void OnBankCardNumChanging(global::System.String value);
        partial void OnBankCardNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayBank
        {
            get
            {
                return _PayBank;
            }
            set
            {
                OnPayBankChanging(value);
                ReportPropertyChanging("PayBank");
                _PayBank = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayBank");
                OnPayBankChanged();
            }
        }
        private global::System.String _PayBank;
        partial void OnPayBankChanging(global::System.String value);
        partial void OnPayBankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayBankDes
        {
            get
            {
                return _PayBankDes;
            }
            set
            {
                OnPayBankDesChanging(value);
                ReportPropertyChanging("PayBankDes");
                _PayBankDes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayBankDes");
                OnPayBankDesChanged();
            }
        }
        private global::System.String _PayBankDes;
        partial void OnPayBankDesChanging(global::System.String value);
        partial void OnPayBankDesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BankName
        {
            get
            {
                return _BankName;
            }
            set
            {
                OnBankNameChanging(value);
                ReportPropertyChanging("BankName");
                _BankName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BankName");
                OnBankNameChanged();
            }
        }
        private global::System.String _BankName;
        partial void OnBankNameChanging(global::System.String value);
        partial void OnBankNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitCode
        {
            get
            {
                return _UnitCode;
            }
            set
            {
                OnUnitCodeChanging(value);
                ReportPropertyChanging("UnitCode");
                _UnitCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitCode");
                OnUnitCodeChanged();
            }
        }
        private global::System.String _UnitCode;
        partial void OnUnitCodeChanging(global::System.String value);
        partial void OnUnitCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CaseCode
        {
            get
            {
                return _CaseCode;
            }
            set
            {
                OnCaseCodeChanging(value);
                ReportPropertyChanging("CaseCode");
                _CaseCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CaseCode");
                OnCaseCodeChanged();
            }
        }
        private global::System.String _CaseCode;
        partial void OnCaseCodeChanging(global::System.String value);
        partial void OnCaseCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AutoId
        {
            get
            {
                return _AutoId;
            }
            set
            {
                OnAutoIdChanging(value);
                ReportPropertyChanging("AutoId");
                _AutoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoId");
                OnAutoIdChanged();
            }
        }
        private global::System.Int32 _AutoId;
        partial void OnAutoIdChanging(global::System.Int32 value);
        partial void OnAutoIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitName
        {
            get
            {
                return _UnitName;
            }
            set
            {
                OnUnitNameChanging(value);
                ReportPropertyChanging("UnitName");
                _UnitName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitName");
                OnUnitNameChanged();
            }
        }
        private global::System.String _UnitName;
        partial void OnUnitNameChanging(global::System.String value);
        partial void OnUnitNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProSectionId
        {
            get
            {
                return _ProSectionId;
            }
            set
            {
                OnProSectionIdChanging(value);
                ReportPropertyChanging("ProSectionId");
                _ProSectionId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProSectionId");
                OnProSectionIdChanged();
            }
        }
        private global::System.String _ProSectionId;
        partial void OnProSectionIdChanging(global::System.String value);
        partial void OnProSectionIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BidMoneyType
        {
            get
            {
                return _BidMoneyType;
            }
            set
            {
                OnBidMoneyTypeChanging(value);
                ReportPropertyChanging("BidMoneyType");
                _BidMoneyType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BidMoneyType");
                OnBidMoneyTypeChanged();
            }
        }
        private global::System.String _BidMoneyType;
        partial void OnBidMoneyTypeChanging(global::System.String value);
        partial void OnBidMoneyTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LinkPerson
        {
            get
            {
                return _LinkPerson;
            }
            set
            {
                OnLinkPersonChanging(value);
                ReportPropertyChanging("LinkPerson");
                _LinkPerson = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinkPerson");
                OnLinkPersonChanged();
            }
        }
        private global::System.String _LinkPerson;
        partial void OnLinkPersonChanging(global::System.String value);
        partial void OnLinkPersonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LinkPersonPhone
        {
            get
            {
                return _LinkPersonPhone;
            }
            set
            {
                OnLinkPersonPhoneChanging(value);
                ReportPropertyChanging("LinkPersonPhone");
                _LinkPersonPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinkPersonPhone");
                OnLinkPersonPhoneChanged();
            }
        }
        private global::System.String _LinkPersonPhone;
        partial void OnLinkPersonPhoneChanging(global::System.String value);
        partial void OnLinkPersonPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LinkPersonMobilTel
        {
            get
            {
                return _LinkPersonMobilTel;
            }
            set
            {
                OnLinkPersonMobilTelChanging(value);
                ReportPropertyChanging("LinkPersonMobilTel");
                _LinkPersonMobilTel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinkPersonMobilTel");
                OnLinkPersonMobilTelChanged();
            }
        }
        private global::System.String _LinkPersonMobilTel;
        partial void OnLinkPersonMobilTelChanging(global::System.String value);
        partial void OnLinkPersonMobilTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String submiter
        {
            get
            {
                return _submiter;
            }
            set
            {
                OnsubmiterChanging(value);
                ReportPropertyChanging("submiter");
                _submiter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("submiter");
                OnsubmiterChanged();
            }
        }
        private global::System.String _submiter;
        partial void OnsubmiterChanging(global::System.String value);
        partial void OnsubmiterChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String submitername
        {
            get
            {
                return _submitername;
            }
            set
            {
                OnsubmiternameChanging(value);
                ReportPropertyChanging("submitername");
                _submitername = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("submitername");
                OnsubmiternameChanged();
            }
        }
        private global::System.String _submitername;
        partial void OnsubmiternameChanging(global::System.String value);
        partial void OnsubmiternameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> submittime
        {
            get
            {
                return _submittime;
            }
            set
            {
                OnsubmittimeChanging(value);
                ReportPropertyChanging("submittime");
                _submittime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("submittime");
                OnsubmittimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _submittime;
        partial void OnsubmittimeChanging(Nullable<global::System.DateTime> value);
        partial void OnsubmittimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsOnline
        {
            get
            {
                return _IsOnline;
            }
            set
            {
                OnIsOnlineChanging(value);
                ReportPropertyChanging("IsOnline");
                _IsOnline = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsOnline");
                OnIsOnlineChanged();
            }
        }
        private Nullable<global::System.Int32> _IsOnline;
        partial void OnIsOnlineChanging(Nullable<global::System.Int32> value);
        partial void OnIsOnlineChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayOrderNo
        {
            get
            {
                return _PayOrderNo;
            }
            set
            {
                OnPayOrderNoChanging(value);
                ReportPropertyChanging("PayOrderNo");
                _PayOrderNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayOrderNo");
                OnPayOrderNoChanged();
            }
        }
        private global::System.String _PayOrderNo;
        partial void OnPayOrderNoChanging(global::System.String value);
        partial void OnPayOrderNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TransOrderNo
        {
            get
            {
                return _TransOrderNo;
            }
            set
            {
                OnTransOrderNoChanging(value);
                ReportPropertyChanging("TransOrderNo");
                _TransOrderNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TransOrderNo");
                OnTransOrderNoChanged();
            }
        }
        private global::System.String _TransOrderNo;
        partial void OnTransOrderNoChanging(global::System.String value);
        partial void OnTransOrderNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SearchOrderNo
        {
            get
            {
                return _SearchOrderNo;
            }
            set
            {
                OnSearchOrderNoChanging(value);
                ReportPropertyChanging("SearchOrderNo");
                _SearchOrderNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SearchOrderNo");
                OnSearchOrderNoChanged();
            }
        }
        private global::System.String _SearchOrderNo;
        partial void OnSearchOrderNoChanging(global::System.String value);
        partial void OnSearchOrderNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OtherOrderNo
        {
            get
            {
                return _OtherOrderNo;
            }
            set
            {
                OnOtherOrderNoChanging(value);
                ReportPropertyChanging("OtherOrderNo");
                _OtherOrderNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OtherOrderNo");
                OnOtherOrderNoChanged();
            }
        }
        private global::System.String _OtherOrderNo;
        partial void OnOtherOrderNoChanging(global::System.String value);
        partial void OnOtherOrderNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PayTotalMoney
        {
            get
            {
                return _PayTotalMoney;
            }
            set
            {
                OnPayTotalMoneyChanging(value);
                ReportPropertyChanging("PayTotalMoney");
                _PayTotalMoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayTotalMoney");
                OnPayTotalMoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _PayTotalMoney;
        partial void OnPayTotalMoneyChanging(Nullable<global::System.Decimal> value);
        partial void OnPayTotalMoneyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RtnTotalMoney
        {
            get
            {
                return _RtnTotalMoney;
            }
            set
            {
                OnRtnTotalMoneyChanging(value);
                ReportPropertyChanging("RtnTotalMoney");
                _RtnTotalMoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RtnTotalMoney");
                OnRtnTotalMoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _RtnTotalMoney;
        partial void OnRtnTotalMoneyChanging(Nullable<global::System.Decimal> value);
        partial void OnRtnTotalMoneyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RtnRateMoney
        {
            get
            {
                return _RtnRateMoney;
            }
            set
            {
                OnRtnRateMoneyChanging(value);
                ReportPropertyChanging("RtnRateMoney");
                _RtnRateMoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RtnRateMoney");
                OnRtnRateMoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _RtnRateMoney;
        partial void OnRtnRateMoneyChanging(Nullable<global::System.Decimal> value);
        partial void OnRtnRateMoneyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RtnRateDate
        {
            get
            {
                return _RtnRateDate;
            }
            set
            {
                OnRtnRateDateChanging(value);
                ReportPropertyChanging("RtnRateDate");
                _RtnRateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RtnRateDate");
                OnRtnRateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RtnRateDate;
        partial void OnRtnRateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRtnRateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TransTime
        {
            get
            {
                return _TransTime;
            }
            set
            {
                OnTransTimeChanging(value);
                ReportPropertyChanging("TransTime");
                _TransTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransTime");
                OnTransTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _TransTime;
        partial void OnTransTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnTransTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SearchTime
        {
            get
            {
                return _SearchTime;
            }
            set
            {
                OnSearchTimeChanging(value);
                ReportPropertyChanging("SearchTime");
                _SearchTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SearchTime");
                OnSearchTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _SearchTime;
        partial void OnSearchTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnSearchTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClearFlag
        {
            get
            {
                return _ClearFlag;
            }
            set
            {
                OnClearFlagChanging(value);
                ReportPropertyChanging("ClearFlag");
                _ClearFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClearFlag");
                OnClearFlagChanged();
            }
        }
        private Nullable<global::System.Int32> _ClearFlag;
        partial void OnClearFlagChanging(Nullable<global::System.Int32> value);
        partial void OnClearFlagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsBidAgain
        {
            get
            {
                return _IsBidAgain;
            }
            set
            {
                OnIsBidAgainChanging(value);
                ReportPropertyChanging("IsBidAgain");
                _IsBidAgain = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBidAgain");
                OnIsBidAgainChanged();
            }
        }
        private Nullable<global::System.Int32> _IsBidAgain;
        partial void OnIsBidAgainChanging(Nullable<global::System.Int32> value);
        partial void OnIsBidAgainChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ABOCPayOrderNo
        {
            get
            {
                return _ABOCPayOrderNo;
            }
            set
            {
                OnABOCPayOrderNoChanging(value);
                ReportPropertyChanging("ABOCPayOrderNo");
                _ABOCPayOrderNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ABOCPayOrderNo");
                OnABOCPayOrderNoChanged();
            }
        }
        private global::System.String _ABOCPayOrderNo;
        partial void OnABOCPayOrderNoChanging(global::System.String value);
        partial void OnABOCPayOrderNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ABOCReturnOrderNo
        {
            get
            {
                return _ABOCReturnOrderNo;
            }
            set
            {
                OnABOCReturnOrderNoChanging(value);
                ReportPropertyChanging("ABOCReturnOrderNo");
                _ABOCReturnOrderNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ABOCReturnOrderNo");
                OnABOCReturnOrderNoChanged();
            }
        }
        private global::System.String _ABOCReturnOrderNo;
        partial void OnABOCReturnOrderNoChanging(global::System.String value);
        partial void OnABOCReturnOrderNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayAccNo
        {
            get
            {
                return _PayAccNo;
            }
            set
            {
                OnPayAccNoChanging(value);
                ReportPropertyChanging("PayAccNo");
                _PayAccNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayAccNo");
                OnPayAccNoChanged();
            }
        }
        private global::System.String _PayAccNo;
        partial void OnPayAccNoChanging(global::System.String value);
        partial void OnPayAccNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayAccDbName
        {
            get
            {
                return _PayAccDbName;
            }
            set
            {
                OnPayAccDbNameChanging(value);
                ReportPropertyChanging("PayAccDbName");
                _PayAccDbName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayAccDbName");
                OnPayAccDbNameChanged();
            }
        }
        private global::System.String _PayAccDbName;
        partial void OnPayAccDbNameChanging(global::System.String value);
        partial void OnPayAccDbNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayAccDBBank
        {
            get
            {
                return _PayAccDBBank;
            }
            set
            {
                OnPayAccDBBankChanging(value);
                ReportPropertyChanging("PayAccDBBank");
                _PayAccDBBank = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayAccDBBank");
                OnPayAccDBBankChanged();
            }
        }
        private global::System.String _PayAccDBBank;
        partial void OnPayAccDBBankChanging(global::System.String value);
        partial void OnPayAccDBBankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ABOCOrderNo
        {
            get
            {
                return _ABOCOrderNo;
            }
            set
            {
                OnABOCOrderNoChanging(value);
                ReportPropertyChanging("ABOCOrderNo");
                _ABOCOrderNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ABOCOrderNo");
                OnABOCOrderNoChanged();
            }
        }
        private global::System.String _ABOCOrderNo;
        partial void OnABOCOrderNoChanging(global::System.String value);
        partial void OnABOCOrderNoChanged();

        #endregion

    
    }

    #endregion

    
}
